services:
  debezium-database:
    image: postgres:16.3
    container_name: debezium-database
    hostname: debezium-database
    command: [ 'postgres', '-c', 'wal_level=logical' ]
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=debezium
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./database/:/var/lib/postgresql/data
    networks:
      - cdc-net

  zookeeper:
    image: bitnami/zookeeper:3.9.2
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - cdc-net

  debezium:
    image: debezium/connect:3.0
    container_name: debezium
    hostname: debezium
    ports:
      - 8083:8083
    depends_on:
      - debezium-database
      - zookeeper
      - kafka
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my-connect-configs
      - OFFSET_STORAGE_TOPIC=my-connect-offsets
      - BOOTSTRAP_SERVERS=kafka:19092
    links:
      - zookeeper:zookeeper
      - kafka:kafka
    volumes:
      - ./debezium/kafka_data:/kafka/data
      - ./debezium/kafka_logs:/kafka/logs
      - ./debezium/kafka_config:/kafka/config
    networks:
      - cdc-net

  # debezium-ui:
  #   image: debezium/debezium-ui:latest
  #   container_name: debezium-ui
  #   ports:
  #     - 8090:8090
  #   depends_on:
  #     - debezium-database
  #     - zookeeper
  #     - debezium
  #   environment:
  #     KAFKA_CONNECT_URIS: http://debezium:8083
  #   networks:
  #     - cdc-net

  kafka:
    image: bitnami/kafka:3.7.1
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      - TZ=Asia/Jakarta
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:19092,PLAINTEXT_HOST://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:19092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    networks:
      - cdc-net
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    hostname: kafka-ui
    depends_on:
      - kafka
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Jakarta
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:19092
    networks:
      - cdc-net
  # elasticsearch:
  #   container_name: elasticsearch
  #   hostname: elasticsearch
  #   image: bitnami/elasticsearch:8
  #   depends_on:
  #     - zookeeper
  #     - kafka
  #     - debezium-database
  #   ports:
  #     - '9200:9200'
  #     - '9300:9300'
  #   volumes:
  #     - './elasticsearch:/bitnami/elasticsearch/data'
  #   networks:
  #     - cdc-net

networks:
  cdc-net:
    driver: bridge
