services:
  debezium-database:
    image: postgres:16.3
    container_name: debezium-database
    hostname: debezium-database
    command: [ 'postgres', '-c', 'wal_level=logical' ]
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=debezium
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./database/:/var/lib/postgresql/data
    networks:
      - debe-net

  # zookeeper:
  #   image: bitnami/zookeeper:3.9.2
  #   container_name: zookereper
  #   hostname: zookeeper
  #   ports:
  #     - 2181:2181
  #   environment:
  #     ALLOW_ANONYMOUS_LOGIN: "yes"
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #     ZOO_4LW_COMMANDS_WHITELIST: "*"
  #     ZOO_ENABLE_AUTH: "yes"
  #     ZOO_CLIENT_USER: "admin"
  #     ZOO_CLIENT_PASSWORD: "admin"
  #   networks:
  #     - debe-net

  debezium:
    image: debezium/connect:3.0
    container_name: debezium
    hostname: debezium
    ports:
      - 8083:8083
    depends_on:
      - debezium-database
      - kafka
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my-connect-configs
      - OFFSET_STORAGE_TOPIC=my-connect-offsets
      - BOOTSTRAP_SERVERS=kafka:9092
    links:
      - kafka:kafka
    networks:
      - debe-net

  kafka:
    image: bitnami/kafka:3.7.1
    container_name: kafka
    hostname: kafka
    ports:
      - '9092:9092'
    volumes:
      - ./kafka:/bitnami/kafka
    environment:
      - TZ=Asia/Jakarta
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:19092,PLAINTEXT_HOST://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:19092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    networks:
      - debe-net

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Jakarta
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:19092
  # debezium-ui:
  #   image: debezium/debezium-ui:latest
  #   container_name: debezium-ui
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - debezium-database
  #     - debezium
  #   environment:
  #     KAFKA_CONNECT_URIS: http://debezium:8083
  #   networks:
  #     - debe-net
  solr:
    image: solr:9.6.1
    container_name: solr
    hostname: solr
    ports:
      - 8983:8983
    volumes:
      - ./solrdata:/var/solr
    user: root
    command: bash -c " chown -R 8983:8983 /var/solr && runuser -u solr -- solr-precreate default-core"
    networks:
      - debe-net

networks:
  debe-net:
    driver: bridge
