services:
  kong-database:
    image: postgres:16.3
    container_name: kong-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=kong-db
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./database/:/var/lib/postgresql/data
    networks:
      - kong-networks

  kong-migrations-up:
    image: kong:3.7.1
    command: kong migrations up
    container_name: kong-migrations
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_DATABASE=kong-db
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=postgres
      - KONG_PG_PASSWORD=123456
    networks:
      - kong-networks

  kong-gateway:
    depends_on:
      - kong-database
    container_name: kong-gateway
    image: kong:3.7.1
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_DATABASE=kong-db
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=postgres
      - KONG_PG_PASSWORD=123456
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_PROXY_LISTEN_SSL=0.0.0.0:8443
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8002:8002"
    networks:
      - kong-networks

networks:
  kong-networks:
    driver: bridge
